projects:
  amptodo:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: tr3atrxw4fhz3pdhxnnkgswxtm
      endpoints:
        prod: >-
          https://wlo2xzzsbjgetkhauc3dlij5qy.appsync-api.us-east-1.amazonaws.com/graphql
